export type ViewKey = 'entrance' | 'entry' | 'exit' | 'north' | 'east' | 'south' | 'west' | 'transit'

export type SceneRole = 'hub' | 'explore' | 'exit' | 'transit'

export type HotspotKind = 'knowledge' | 'question' | 'navigation' | 'empty'

export type Point = [number, number]

export interface KnowledgeCard {
  id: string
  title: string
  body: string
  teacherCue?: string
}

export interface Hotspot {
  id: string
  label: string
  x: number
  y: number
  width: number
  height: number
  kind: HotspotKind
  knowledgeId?: string
  targetSceneId?: string
  /**
   * Optional object contour in scene-percent coordinates (0-100).
   * When present, the UI uses this polygon as the clickable/highlight shape
   * instead of showing a rectangular guide box.
   */
  points?: Point[]
  /** Object id generated by the automatic segmentation pipeline. */
  objectRef?: string
}

export interface Scene {
  id: string
  roomId: string
  view: ViewKey
  role: SceneRole
  title: string
  asset?: string
  visualClass: string
  hotspots: Hotspot[]
  turnLeftSceneId?: string
  turnRightSceneId?: string
  /** Optional JSON generated by tools/auto_segment.py. */
  objectMapAsset?: string
}

export interface RoomDefinition {
  id: string
  title: string
  lockedLocation?: boolean
}

export interface WorldManifest {
  id: string
  title: string
  version: string
  startSceneId: string
  rooms: Record<string, RoomDefinition>
  scenes: Record<string, Scene>
}
